### ISSUE TITLE
error : load weights

### ISSUE THREAD

**Issue by Bonsen** [Vladkryvoruchko/PSPNet-Keras-tensorflow#46]
I want to run train.py and I get:
Importing weights from weights/npy/pspnet50_ade20k.npy
input_1
conv1_1_3x3_s2
'conv1_1_3x3_s2'
conv1_1_3x3_s2_bn
Traceback (most recent call last):
  File "train.py", line 152, in <module>
    args.batch, args.weights, args.initial_epoch, args.model, args.sep)
  File "train.py", line 98, in train
    set_npy_weights(pre_trained, model)
  File "train.py", line 32, in set_npy_weights
    mean = weights[layer.name]['mean'].reshape(-1)
KeyError: 'conv1_1_3x3_s2_bn'

If I use load_model, it shows:
    model = load_model("./weights/keras/pspnet50_ade20k.h5")
  File "~/.local/lib/python3.5/site-packages/keras/models.py", line 268, in load_model
    raise ValueError('No model found in config file.')
ValueError: No model found in config file.

If i use np.load(h5_path).item(), it shows:
  File "train.py", line 155, in <module>
    train(args.datadir, args.logdir, (473, 473), args.classes, args.resnet_layers,
  File "train.py", line 99, in train
    input_shape=input_size)
  File "train.py", line 27, in set_npy_weights
    #weights = np.load(npy_weights_path,encoding="bytes").item()
  File "~/.local/lib/python3.5/site-packages/numpy/lib/npyio.py", line 443, in load
    "Failed to interpret file %s as a pickle" % repr(file))
OSError: Failed to interpret file 'weights/keras/pspnet50_ade20k.h5' as a pickle

**Comment by Bonsen** [comment]
After I use np.load(,encoding="latin1"), everything is OK. (not "bytes")
